server.port: 8081

database-service:
  url: localhost:9090

spring:
  application:
    name: Kafka-application-service
  cloud:
    function:
      definition: writeCourseIntoDatabase
    stream:
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            zkNodes: localhost:2181
            configuration:
              key-serializer: org.apache.kafka.common.serialization.StringSerializer
              value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            functions:
              writeCourseIntoDatabase:
                applicationId: writeCourseIntoDatabase
      bindings:
        writeCourseIntoDatabase-in-0:
          destination: topicCoursePmuSource1
        writeCourseIntoDatabase-out-0:
          destination: topicCoursePmuDestination